### PR TITLE
fix duplicate reported error messages

### PR DESCRIPTION
**Pull request by GavinJoyce**
fixes https://github.com/kratiahuja/broccoli-tslinter/issues/2

/cc @kratiahuja this will allow me to complete the [integration of `broccoli-tslinter` into glimmer](https://github.com/tildeio/glimmer/pull/214) (perhaps you might cut a new release once this issue is resolved?)

### CODE REVIEW

**Comment by GavinJoyce** [comment]
Ping @kratiahuja

**Comment by kratiahuja** [comment]
hey @GavinJoyce, sorry I was on vacation and I am still catching up with my open source projects. Your PR sounds correct to me.

**Comment by kratiahuja** [comment]
@GavinJoyce v1.0.1 has been released. Please let me know if there any issues. Thanks for the PR!

**Comment by GavinJoyce** [comment]
Great, thanks

**Pull request merged**
